### ISSUE TITLE
Title of latest article is incorrect

### ISSUE THREAD

**Issue by wconrad** [onebree/onebree.github.io#1]
The title "Do not rely on `ruby -c` for accurate syntax analysis" is inaccurate: -c does fully check for syntax errors.  A syntax error is one where the language does not conform to its grammar.  Errors where the grammar is incorrect but the program cannot function because, for example, the variable does not exist, are semantic errors and cannot be caught by syntactic analysis.

A statically typed language can catch many semantic errors at compile time.  Programmers may loosely refer to all errors caught at compile time as "syntax errors," which may be where the confusion comes from.

**Comment by onebree** [comment]
Thank you, Wayne. I will add additional examples, too, like using a comma instead of a period when trying to call a method. I will also find/add a link about syntactic vs semantic errors in programming.
